USE COMPANY;
CREATE TABLE EMPLOYEE(
ID INT PRIMARY KEY NOT NULL,
NAME VARCHAR(50),
DEPARTMENT VARCHAR(50)
);

INSERT INTO EMPLOYEE(ID, NAME, DEPARTMENT)
VALUES(101, "MOHIT", "CS"), (102, "SOHIT", "IT"),(103, "MONY", "TCS"),(104, "SONAM KAPPOR", "BCS");
SELECT * FROM EMPLOYEE;
update employee
set department = "BCS"
where id =102;
SELECT * FROM EMPLOYEE;
delete from employee
where id =102;
SELECT * FROM EMPLOYEE;







